const langData = {
    "uz": {
      "home": "Sayt yaratish",
      "about": "SEO va Daromadni Oshirish",
      "contact": "Kontakt",
      "xitmatlar": "Xizmatlar",
      "articl": "Maqolalar",
      "our_work": "Ish namunalarimiz",
      "price": "Narxlar",
      "nav_text": "Buyurtma berish",
      "section1_text1.1": "CMD-TECH jamoasining ",
      "section1_text1.2": "portfoliosi ",
      "section1_text2": "Sizning biznesingiz uchun CMD-TECH bilan hamkorlik kutilmagan va ajoyib burilish bo'lishi mumkin. Bu hamkorlik savdo hajmini oshirishga yordam beradigan bir tomondan, saytingizni rivojlantirish va targ'ib qilishda samarali hamkor bo'lishi bilan ham muhimdir.",
      "section1_text4": "Hoziroq biz bilan",
      "section1_text5": "Bog'lanish",
      "work_text1": "Ming marta eshitgandan bir marta ko'rgan ma'qul",
      "work_text2": "Turli sohalardagi tashkilotlar bizning OQILA veb-studiyamiz xizmatlaridan foydalanganlar. Ularning hamkorlikdagi natijalari sizga biz bilan kelajakdagi hamkorligingiz qanday bo'lishi haqida tasavvur beradi. Bizning mijozlarimiz bilan olib borgan ishlarimiz orqali siz bizning professional yondashuvimiz, ijodkorligimiz va yuqori sifatli xizmatlarimizni ko'rishingiz mumkin. Bu sizga biz bilan ishlash jarayonida qanday natijalarga erishishingiz mumkinligini ko'rsatib beradi.",
      "section2_text1.1": "SIZNING BIZNESINGIZ HAM",
      "section2_text1.2": "SIFATLI WEB SAYTGA VA INTERNET REKLAMAGA LOYIQ",
      "section2_text2": "Bizning internet marketing mutaxassislarimiz ko’plab firmalar uchun saytga tashriflar sonini, qo’ng’iroqlar sonini va, albatta, daromadni oshirib berishni. Ular bu ishlarni siz uchun ham qilishga tayyor.",
      "section2_text3": "Ishni paysalga solmang",
      "comment_text1": "Qilgan sarmoyalarimizdan afsuslanmadik",
      "comment_text2": "2,000 dan ortiq hamkorlarimiz bor. Ularning har oylik daromadlari qiyin formula bilan hisoblanadi",
      "comment_text3": "CMD-TECH jamoasiga shuni avtomatlashtirish bo’yicha yuzlandik. Dasturni yaratib berishdi, ishlayapti.",
      "comment_text4": "Hozir bu ishni boshqa dasturchilarga ishonib topshirishni ko’z oldimga keltirolmayman",
      "comment_text6": "Saytsiz eksportga ishlash qiyin<",
      "comment_text7": "Biz tabiiy tolalardan kundalik va maxsus kiyimlar ishlab chiqarish bilan shug’ullanamiz. 90% eksportga ishlaganimiz uchun, korxonamiz to’liq quvvatini ko’rsatadigan sayt kerak bo’ldi.",
      "comment_text8": "CMD-TECH jamoasiga saytimiz dizaynini ishonib topshirdik. Natija kutilganidek bo’ldi. Muhimi ular boshqa davlat odamlariga nima yoqishini bilishadi. Juda xursandmiz.",
      "comment_text9": "Barchaga tavsiya qilaman!",
      "comment_text10": "«Kichik mablag’ evaziga yillab reklama qilish» Faqat shu shart bilan CMD-TECH bilan hamkorlik qilishga rozi bo’ldim. Shunda menga sayt yaratish va uni tabiiy ravishda Googleda yuqoriga olib chiqish SEO xizmatini taklif qilishdi.",
      "comment_text11": "SEO nimaligini uncha yaxshi tushunmasam ham, o’shanda taklifga rozi bo’ldim, chunki reklamaga katta pul tikishga na imkonim, na vaqtim bor edi. Natijada 2017 yildan beri reklama haqida o’ylamayman, lekin zakazlar to’xtagani yo’q. Kichik ishimni katta biznesga aylantirdim. Ko’plar SEO reklamani umuman hisobga olishmaydi. Menimcha, agar biznesim uzoqqa borsin desangiz, birinchi ishni shundan boshlang.",
      "comment_text12": "Shukrullo, Tarmoqli marketing asoschisi, Namangan",
      "comment_text13": "Kimyoviy o’g’it kompaniyasi",
      "comment_text14": "Yurtimizdagi dehqonchilik xo’jaliklari va xorijdagi importyor hamkorlarimiz uchun maxsus veb sayt ochmoqchi edik. Bu ishni CMD-TECH jamoasi o’ylaganimizdan ortiqroq bajardi.",
      "comment_text15": "Saytga tashrif buyuruvchilar soni ko’payib, saytimning taniqliligi oshganidan so’ng, CMD-TECH jamoasiga bekorga sarmoya kiritmagan ekanman degan fikrga keldim.",
      "comment_text16": "Beton va shag’al yetkazish kompaniyasi",
      "comment_text17": "Farg’onada joylashgan bo’lsak ham Toshkentning katta qismini beton quduqlar bilan ta’minlaymiz. Brendimizni tanitish uchun logotip va internet sayt yaratish masalasida CMD-TECH jamoasiga chiqdik.",
      "comment_text18": "Saytimiz dizayni juda zo’r chiqdi. Rahmat",
      "comment_text50": "Shukrullo, Tarmoqli marketing asoschisi, Namangan",
      "comment_text51": "Shukrullo, Tarmoqli marketing asoschisi, Namangan",
      "comment_text52": "Shukrullo, Tarmoqli marketing asoschisi, Namangan",
      "comment_text53": "Shukrullo, Tarmoqli marketing asoschisi, Namangan",
      "comment_text54": "Shukrullo, Tarmoqli marketing asoschisi, Namangan",
      "comment_text55": "Shukrullo, Tarmoqli marketing asoschisi, Namangan",

      "footer_text1": "Biz 100 dan ortiq mijozlarimizni xursand qildik. Sizga qanday yordam berishimiz mumkinligini bilish uchun biz bilan bog'laning!", 
      "footer_text2": "Yuz marta o'qigandan ko'ra, bir marta gaplashish yaxshiroqdir. Sizning biznesingizni tahlil qilaylik va siz uchun maxsus taklif tayyorlaylik.", 
      "footer_text3": "O'zingizning biznesingizni targ'ib qilishni kechiktirmang, aks holda kimdir bu imkoniyatdan foydalanadi.", 
      "footer_text4": "Bizga hozir qo'ng'iroq qiling:", 
      "footer_text5": "Aloqalar", 
      "footer_text6": "Kattaqo'rg'on ko'ch. 20-uy, Toshkent Shahar",
      "footer_text7": "Menyu",
      "footer_text8": "Qadriyatlarimiz",
      "footer_text9": "CMD-TECh jamoasi",
      "footer_text10": "Jamoamizga qo'shiling",
      "footer_text811": "Aloqalar",
      "footer_text12": "Biz haqimizda", 
      "footer_text13": "Maqolalar", 
      "footer_text14": "Ish namunalarimiz", 
      "footer_text15": "Mijozlarimiz fikrlari", 
      "footer_text16": "Loyihalar va nashrlar", 
      "footer_text17": "Bizni Kuzatib Boring:",      
      "footer_text2.2": "Arizangizni yuboring", 
      "btn_text1": "Mutaxassis bilan bog'lanish",
      "btn_text2": "Ismingiz: *",
      "btn_text3": "Telefon raqamingiz: *",
      "btn_text4": "Kompaniya nomi: *",     
  
      
    },
    "ru": {
      "home": "Создать сайт",
      "about": "SEO и Увеличение дохода",
      "product": "Дизайн и Брендинг",
      "contact": "Контакт",
      "xitmatlar": "Услуги",
      "articl": "Cтатья",
      "our_work": "Портфолио",
      "price": "Цены",
      "nav_text": "Разместить заказ",
      "section1_text1.1": "команды CMD-TECH ",
      "section1_text1.2": " портфолио",
      "section1_text2": "Сотрудничество с CMD-TECH может стать неожиданным и прекрасным поворотом для вашего бизнеса. Такое партнерство важно, с одной стороны, способствовать увеличению продаж, но и быть эффективным партнером в развитии и продвижении вашего сайта.",
      "section1_text4": "С нами прямо сейчас",
      "section1_text5": "Связь",
      "work_text1": "Лучше один раз увидеть, чем тысячу раз услышать",
      "work_text2": "Услугами нашей веб-студии SMART воспользовались организации из различных отраслей. Результаты их сотрудничества дадут вам представление о том, каким будет ваше будущее сотрудничество с нами. Благодаря нашей работе с нашими клиентами вы можете увидеть наш профессиональный подход, креативность и высокое качество услуг. Это покажет вам, каких результатов вы сможете достичь, работая с нами.",
      "section2_text1.1": "ВАШ БИЗНЕС ТОЖЕ",
      "section2_text1.2": "ЗАСЛУЖИВАЕТ КАЧЕСТВЕННЫЙ САЙТ И ИНТЕРНЕТ-РЕКЛАМУ",
      "section2_text2": "Наши специалисты по интернет-маркетингу помогли многим компаниям увеличить посещаемость сайта, звонки и, конечно же, прибыль. Они готовы сделать это и для вас.",
      "section2_text3": "Не принимайте это как должное",
      "comment_text1": "Мы не пожалели о своих инвестициях",
      "comment_text2": "У нас более 2000 партнеров. Их ежемесячный доход рассчитывается по сложной формуле",
      "comment_text3": "Для этой автоматизации мы обратились к команде CMD-TECH. Программу создали, она работает.",
      "comment_text4": "Теперь я не могу себе представить, чтобы доверить эту работу другим программистам.",
      "comment_text6": "Без сайта сложно экспортировать",
      "comment_text7": "Мы занимаемся производством повседневной и специальной одежды из натуральных волокон. Поскольку мы на 90% работаем на экспорт, нам нужен был сайт, который бы показывал все возможности нашей компании.",
      "comment_text8": "Дизайн нашего сайта мы доверили команде CMD-TECH. Результат оказался таким, как ожидалось. Важно то, что они знают, что нравится людям из других стран. Мы очень счастливы.",
      "comment_text9": "Я рекомендую это всем!",
      "comment_text10": "Я согласился сотрудничать с CMD-TECH только при этом условии. Затем мне предложили услугу SEO по созданию сайта и его естественному выводу в топ Google.",
      "comment_text11": "Хоть я и не очень хорошо разбирался в SEO, я тогда согласился на предложение, так как у меня не было ни возможности, ни времени вкладывать большие деньги в рекламу. В итоге о рекламе я не думал с 2017 года, но заказы не прекратились. Я превратил свой маленький бизнес в большой бизнес. Многие вообще не рассматривают SEO-рекламу. На мой взгляд, если вы хотите, чтобы мой бизнес пошел далеко, начните с этого в первую очередь.",
      "comment_text13": "Компания по производству химических удобрений",
      "comment_text14": "Мы хотели открыть специальный сайт для сельскохозяйственных ферм в нашей стране и наших партнеров-импортеров за рубежом. Команда CMD-TECH сделала больше, чем мы думали.",
      "comment_text15": "После того, как количество посетителей сайта увеличилось и возросла популярность моего сайта, я пришел к выводу, что не зря вложил деньги в команду CMD-TECH.",
      "comment_text16": "Компания по доставке бетона и гравия",
      "comment_text17": "Хоть мы и находимся в Фергане, бетонными колодцами мы обеспечиваем большую часть Ташкента. Мы обратились в команду CMD-TECH для создания логотипа и сайта для продвижения нашего бренда.",
      "comment_text18": "Дизайн нашего сайта получился очень удачным. Спасибо",
      "comment_text50": "Шукрулло, основатель компании Network Marketing, Наманган",
      "comment_text51": "Шукрулло, основатель компании Network Marketing, Наманган",
      "comment_text52": "Шукрулло, основатель компании Network Marketing, Наманган",
      "comment_text53": "Шукрулло, основатель компании Network Marketing, Наманган",
      "comment_text54": "Шукрулло, основатель компании Network Marketing, Наманган",
      "comment_text55": "Шукрулло, основатель компании Network Marketing, Наманган",
      "footer_text1": "Мы осчастливили более 100 клиентов. Свяжитесь с нами, чтобы узнать, как мы можем вам помочь!", 
      "footer_text2": "Лучше один раз сказать, чем сто раз прочитать. Давайте проанализируем ваш бизнес и подготовим для вас специальное предложение.", 
      "footer_text3": "Не откладывайте продвижение своего бизнеса, иначе этим воспользуется кто-то другой.", 
      "footer_text4": "Позвоните нам сейчас:", 
      "footer_text5": "Контакты", 
      "footer_text6": "Каттакоргон ул. 20, город Ташкент", 
      "footer_text7": "Меню", 
      "footer_text8": "Наши ценности",
      "footer_text9": "Команда CMD-TECH",
      "footer_text10": "Присоединиться к нашей команде",
      "footer_text11": "Контакты",
      "footer_text12": "о нас", 
      "footer_text13": "Статьи", 
      "footer_text14": "Наши образцы работ", 
      "footer_text15": "Мнения наших клиентов", 
      "footer_text16": "Проекты и публикации", 
      "footer_text17": "Подписывайтесь на нас:", 
      "footer_text2.2":"Оставить заявку",
      "btn_text1": "Свяжитесь с экспертом",
      "btn_text2": "Ваше имя: *",
      "btn_text3": "Ваш номер телефона: *",
      "btn_text4": "Название компании: *",
      "": "", 
      "": "", 
      "": "", 
      "": "", 
      "": "", 
      "": "", 
      "": "", 
      "": "", 
      "": "", 
  
  
  
  
    },
    "en": {
      "home": "Create a site",
      "about": "SEO and Monetization",
      "contact": "Contact",
      "xitmatlar": "Services",
      "articl": "Srticles",
      "product": "Design and Branding",
      "our_work": "Our work samples",
      "price": "Prices",
      "nav_text": "Place an order",
      "section1_text1.1": "Complete price list for  ",
      "section1_text1.2": " website development and advertising services",
      "section1_text2": "Need internet marketing services for your business? Leave it to the masters!",
      "section1_text4": "With us right now",
      "section1_text5": "Connection",


      "work_text1": "It is better to see once than to hear a thousand times",
      "work_text2": "Organizations from various industries have used the services of our SMART web studio. The results of their collaboration will give you an idea of ​​what your future collaboration with us will be like. Through our work with our clients, you can see our professional approach, creativity and high quality services. This will show you what results you can achieve when working with us.",
      "section2_text1.1": "YOUR BUSINESS TOO",
      "section2_text1.2": "DESERVES A QUALITY WEBSITE AND INTERNET ADVERTISING",
      "section2_text2": "Our internet marketing experts have helped many companies increase site visits, calls and, of course, profits. They are willing to do these things for you as well.",
      "section2_text3": "Don't take it for granted",
      "comment_text1": "We did not regret our investment",
      "comment_text2": "We have more than 2,000 partners. Their monthly income is calculated by a difficult formula",
      "comment_text3": "We turned to the CMD-TECH team for this automation. They created the program, it is working.",
      "comment_text4": "Now I can't imagine entrusting this work to other programmers",
      "comment_text6": "It is difficult to export without a site",
      "comment_text7": "We are engaged in the production of everyday and special clothes from natural fibers. Since we work for 90% export, we needed a site that would show the full capacity of our company.",
      "comment_text8": "We entrusted the design of our site to the CMD-TECH team. The result was as expected. The important thing is that they know what people from other countries like. We are very happy.",
      "comment_text9": "I recommend it to everyone!",
      "comment_text10": "I agreed to cooperate with CMD-TECH only on this condition. Then I was offered an SEO service to build a site and get it to the top of Google naturally.",
      "comment_text11": "Even though I didn't understand SEO very well, I agreed to the offer at that time, because I had neither the opportunity nor the time to invest a lot of money in advertising. As a result, I have not thought about advertising since 2017, but the orders have not stopped. I turned my small business into a big business. Many do not consider SEO advertising at all. In my opinion, if you want my business to go far, start with this first thing.",
      "comment_text13": "Chemical fertilizer company",
      "comment_text14": "We wanted to open a special website for agricultural farms in our country and our importing partners abroad. The CMD-TECH team did more than we thought.",
      "comment_text15": "After the number of visitors to the site increased and the popularity of my site increased, I came to the conclusion that I did not invest in the CMD-TECH team in vain.",
      "comment_text16": "Concrete and gravel delivery company",
      "comment_text17": "Although we are located in Fergana, we provide concrete wells to most of Tashkent. We went to the CMD-TECH team to create a logo and a website to promote our brand.",
      "comment_text18": "The design of our site turned out very well. Thank you",
      "comment_text50": "Shukrullo, founder of Network Marketing, Namangan",
      "comment_text51": "Shukrullo, founder of Network Marketing, Namangan",
      "comment_text52": "Shukrullo, founder of Network Marketing, Namangan",
      "comment_text53": "Shukrullo, founder of Network Marketing, Namangan",
      "comment_text54": "Shukrullo, founder of Network Marketing, Namangan",
      "comment_text55": "Shukrullo, founder of Network Marketing, Namangan",


      "footer_text1": "We have made more than 100 customers happy. Contact us to find out how we can help you!", 
      "footer_text2": "It is better to talk once than read a hundred times. Let us analyze your business and prepare a special offer for you.", 
      "footer_text3": "Don't delay promoting your business, or someone else will take advantage of it.", 
      "footer_text4": "Call us now:", 
      "footer_text5": "Connections", 
      "footer_text6": "Kattakorgon St. 20, Tashkent City",
      "footer_text7": "Menu",
      "footer_text8": "Our values",
      "footer_text9": "CMD-TECh team",
      "footer_text10": "Join our team",
      "footer_text811": "Connections",
      "footer_text12": "about Us", 
      "footer_text13": "Articles", 
      "footer_text14": "Our work samples", 
      "footer_text15": "Our customers' opinions", 
      "footer_text16": "Projects and publications", 
      "footer_text17": "Follow us:",
      "footer_text2.2": "Submit your application",
      "btn_text1": "Contact an expert",
      "btn_text2": "Your name: *",
      "btn_text3": "Your phone number: *",
      "btn_text4": "Company name: *",
      "": "",
      "": "",
      "": "",
      "": "",
      "": "",
      "": "",
      "": "",
      "": "",
      "": "",
      "": "",  
    }
  };
  
  const langElements = document.querySelectorAll('.lang');
  
  function changeLanguage(language) {
    selectedLanguage = language;
    langElements.forEach(el => {
      el.textContent = langData[selectedLanguage][el.getAttribute('key')];
    });
  }
  
  
  
  // Tilni qayta belgilash
  let selectedLanguage = 'ru';
  langElements.forEach(el => {
    el.textContent = langData[selectedLanguage][el.getAttribute('key')];
  });
  
  const langButtons = document.querySelectorAll('.lang-button');
  langButtons.forEach(btn => {
  btn.addEventListener('click', () => {
    changeLanguage(btn.dataset.lang);
    langButtons.forEach(btn => {
      btn.classList.remove('active_lang');
    });
    btn.classList.add('active_lang');
  });
  });