const langData = {
    "uz": {
      "home": "Sayt yaratish",
      "about": "SEO va Daromadni Oshirish",
      "product": "Dizayn va Brending",
      "our_work": "Ish namunalarimiz",
      "price": "Narxlar",
      "nav_text": "Buyurtma berish",
      "section1_text1.1": "Veb-sayt yaratish va ",
      "section1_text1.2": " reklama xizmatlari uchun to'liq narx ro'yxati",
      "section1_text2": "Biznesingiz uchun internet marketing xizmatlari kerakmi? Buni faqat o’z ishining ustalariga topshiring!",
      "section1_text3": "Chumchuq so’ysa ham qassob so’ysin. O’zingizni ortiqcha xarajatlardan saqlang.",
      "section1_text4": "Hoziroq biz bilan",
      "section1_text5": "Bog'lanish",
      "price_text1": "SEO Xizmat narxi",
      "price_text2": "4.500.000 dan",
      "price_text3": "Hozirgi zamonning eng mashhur va foydali marketing xizmatlaridan biri bu SEO - bu orqali Google qidiruv tizimida yuqori o'rinlarda bo'lish imkoniyati mavjud. Agar sizning biznesingiz Google'da yuqori sahifalarda bo'lsa, bu mijozlarning sizni osonroq topishiga va shu orqali ko'proq daromad topishingizga yordam beradi. Bunday usul, sizning biznesingiz uchun daromad olishning eng samarali yo'llaridan biridir.",
      "price_text4": " Batafsil",
      "price_text5": "Sayt ochish narxi",
      "price_text6": "3.500.000 dan",
      "price_text7": "Biror biznes egasining o'z veb-saytiga ega bo'lishi, mijozlarning ishonchini qozonishda muhim rol o'ynaydi. Bu sayt, istalgan vaqtda, har qanday odamga sizning biznesingiz, uning faoliyati va taklif etilayotgan mahsulotlar to'g'risida zarur ma'lumotlarni taqdim etish imkonini beradi.Veb-sayt, shu bilan birga, mijozlar bilan aloqani mustahkamlash, ularning fikr-mulohazalarini to'plash va biznesingizni yanada rivojlantirish uchun kerakli o'zgarishlarni amalga oshirish uchun muhim vositadir.",
      "price_text8": "Logotip yasash narxi",
      "price_text9": "3.559.000 dan",
      "price_text10": "Logotip, har bir biznes uchun juda muhim bir elementdir. Bu, brendning yuzi bo'lib, birinchi taassurotni yaratishda kalit rol o'ynaydi. Agar logotip malakali va ijodkor dizaynerlar tomonidan ishlab chiqilsa, u nafaqat estetik jihatdan jozibali bo'ladi, balki brendning qadriyatlari va xususiyatlarini ham aks ettiradi. Bunday logotip tezda diqqatni tortadi, mijozlarning xotirasida uzoq muddat saqlanadi va brendning tanilish darajasini sezilarli darajada oshiradi.",
      "price_text11": "Internet do'kon  narxi",
      "price_text12": "14.469.000 dan",
      "price_text13": "Dunyo bo'ylab 1.92 milliarddan ortiq odamlar internet orqali xarid qilishadi, bu dunyo aholisining taxminan to'rtinchi qismiga teng. Online do'kon ochish orqali, bu katta auditoriyadan foydalanib, sezilarli daromad topish imkoniyati mavjud.Shu tariqa, onlayn do'kon orqali siz nafaqat mahalliy, balki xalqaro darajada ham mijozlar bazasini kengaytirishingiz va daromadingizni sezilarli darajada oshirishingiz mumkin.",
      "price_text14": "Google Adword narxi",
      "price_text15": "1.894.000 dan",
      "price_text16": "Google reklama xizmatidan foydalanib, sizning veb-saytingizni atigi bir kun ichida Google qidiruv natijalarining eng yuqori o'rniga chiqarishingiz mumkin. Google orqali reklama qilish sizning biznesingizni ajoyib darajada oshirib, kutilmagan daromadlarga erishish imkonini beradi. Natijada, Google reklama xizmatidan foydalanish, biznesingizni yanada rivojlantirish va daromadlarni ko'paytirish uchun juda samarali vositadir.",
      "price_text17": "Brending yasash narxi",
      "price_text18": "1.900.000 dan",
      "price_text19": "Bir firmaga jozibador nom tanlash juda muhim. Brendingiz yoki firmangiz uchun tanlangan nom uning kelajakdagi muvaffaqiyatiga katta ta'sir ko'rsatishi mumkin. Brendingizga mos nomni tanlash vazifasini professional dizayn studiyasi 'OQILA'ga topshirishingiz mumkin, ular sizning biznesingizga mos, ta'sirchan va yodda qolarli nom yaratishda yordam beradi.",
      "business_text1.1":"CMD-TECH jamoasi har bir mijozga",
      "business_text1.2":"individual yondoshadi",
      "business_text2":"Buyurtma qoldiring",
      "info_text1":"CMD-TECH jamoasi sizga nimalarni taklif qiladi?",
      "info_text2":"Sayt yaratish",
      "info_text3":"Tajribaga ega bo'lgan marketing mutaxassislari sizning daromadingizni oshirish uchun harakat qilishadi. Veb-sayt yaratish ishlari belgilangan aniq texnik talablar asosida va juda tez muddatda bajariladi. Bizning kompaniyamiz tomonidan yaratilgan mobil veb-saytlar, qo'nish sahifalari, korporativ veb-saytlar, e'lonlar va yangiliklar saytlari hamda onlayn do'konlar kabi turli xil xizmatlarni taklif etamiz.",
      "info_text4":"Vizitka sayt",
      "info_text5":"Kompaniyaning veb-sayti, internetda uning asosiy tashrif qog'ozi sifatida, kompaniya haqida eng zarur ma'lumotlarni o'z ichiga olishi lozim. Bu sayt, vizitka sahifasi sifatida, tashrif buyuruvchilarni kompaniyaning xizmatlari va mahsulotlari bilan tanishtirish vazifasini o\'taydi.",
      "info_text6":"Bir sahifali sayt",
      "info_text7":"Landing Page, ya'ni bir sahifali veb-sayt, foydalanuvchilarga qulaylik yaratish maqsadida loyihalashtirilgan. Bu sahifa mijozlarni zarur ma'lumotlar bilan tanishtirishga mo'ljallangan.",
      "info_text8":"Kompaniya sayti",
      "info_text9":"Kompaniyaning veb-sayti, uning internetdagi rasmiy vakili hisoblanadi va uning murakkabligi har xil bo'lishi mumkin. Asosiy maqsadi kompaniya haqida to'liq ma'lumot berish va bu ma'lumotni keng ommaga taqdim etishdir.",
      "info_text10":"Internet do'kon",
      "info_text11":"Onlayn do'kon tashkil etish, savdo ko'rsatkichlarini oshirishga xizmat qiladi. Buning uchun do'konning dizayni xaridorlarni jalb etuvchi va diqqatni tortuvchi bo'lishi juda muhimdir.",
      "info_text12":"Eksklyuziv saytlar",
      "info_text13":"Mutaxassislar har biri noyob bo'lgan saytlarni to'liq yangidan yaratish uchun mehnat qiladilar. Ular saytga o'ziga xos kontent va dizayn yaratib, shu tufayli bu kabi saytlarning narxi odatdagidan biroz yuqori bo'ladi.",
      "info_text14":"Siz qanday turdagi veb-sayt yaratmoqchi bo'lsangiz ham, CMD-TECH jamoasining tajribali mutaxassislari yordamida kerakli natijalarga erishishingiz mumkin.",
      "info_text_title":"Qo'shimcha xizmatlar",
      "info_text15":"Korporativ saytlar yaratish",
      "info_text16":"Turistik firma uchun veb sayt yaratish",
      "info_text17":"Internetda sayt ochish bilan o’quv markazingizni yangi pag’onaga olib chiqing",
      "info_text18":"Tibbiy markaz uchun internetda sayt yaratish xizmati",
      "info_text19":"UZ domenida yangiliklar saytini ochish va tuzish xizmati",
      "info_text20":"Googleda yuridik firma uchun sayt ochish",
      "info_text21":"Ishlab chiqaruvchi korxonalar uchun web sayt ochish xizmatlari",
      "info_text22":"Mashhur brendlar uchun ekskluziv veb sayt ochish",
      "info_text23":"Veb saytlar uchun texnik shart ishlab chiqish",
      "footer_text1": "Biz 100 dan ortiq mijozlarimizni xursand qildik. Sizga qanday yordam berishimiz mumkinligini bilish uchun biz bilan bog'laning!", 
      "footer_text2": "Yuz marta o'qigandan ko'ra, bir marta gaplashish yaxshiroqdir. Sizning biznesingizni tahlil qilaylik va siz uchun maxsus taklif tayyorlaylik.", 
      "footer_text3": "O'zingizning biznesingizni targ'ib qilishni kechiktirmang, aks holda kimdir bu imkoniyatdan foydalanadi.", 
      "footer_text4": "Bizga hozir qo'ng'iroq qiling:", 
      "footer_text5": "Aloqalar", 
      "footer_text6": "Kattaqo'rg'on ko'ch. 20-uy, Toshkent Shahar",
      "footer_text7": "Menyu",
      "footer_text8": "Qadriyatlarimiz",
      "footer_text9": "CMD-TECh jamoasi",
      "footer_text10": "Jamoamizga qo'shiling",
      "footer_text811": "Aloqalar",
      "footer_text12": "Biz haqimizda", 
      "footer_text13": "Maqolalar", 
      "footer_text14": "Ish namunalarimiz", 
      "footer_text15": "Mijozlarimiz fikrlari", 
      "footer_text16": "Loyihalar va nashrlar", 
      "footer_text17": "Bizni Kuzatib Boring:",      
      "footer_text2.2": "Arizangizni yuboring",      
  
      
    },
    "ru": {
      "home": "Создать сайт",
      "about": "SEO и Увеличение дохода",
      "product": "Дизайн и Брендинг",
      "our_work": "Портфолио",
      "price": "Цены",
      "nav_text": "Разместить заказ",
      "section1_text1.1": "Полный прайс-лист на ",
      "section1_text1.2": " услуги по созданию сайтов и рекламе",
      "section1_text2": "Нужны услуги интернет-маркетинга для вашего бизнеса? Оставьте это мастерам!",
      "section1_text3": "Даже если воробья зарежут, пусть его зарежет мясник. Спасите себя от перерасхода средств.",
      "section1_text4": "С нами прямо сейчас",
      "section1_text5": "Связь",
      "price_text1": "Стоимость SEO-услуг",
      "price_text2": "от 4.500.000",
      "price_text3": "Одной из самых популярных и полезных маркетинговых услуг сегодня является SEO, благодаря которому вы можете занять высокие позиции в поисковой системе Google. Если ваш бизнес находится на верхних страницах Google, это поможет клиентам легче вас найти и, таким образом, принести вам больше дохода. Этот метод является одним из наиболее эффективных способов получения дохода для вашего бизнеса.",
      "price_text4": "Более",
      "price_text5": "Стоимость открытия сайта",
      "price_text6": "от 3.500.000",
      "price_text7": "Наличие веб-сайта для владельца бизнеса играет важную роль в завоевании доверия клиентов. Этот сайт позволяет любому человеку в любое время предоставить необходимую информацию о вашем бизнесе, его деятельности и предлагаемых продуктах. Это важный инструмент для внесения необходимых изменений для роста и развития вашего бизнеса.",
      "price_text8": "Стоимость изготовления логотипа",
      "price_text9": "от 3.559.000",
      "price_text10": "Логотип – очень важный элемент для каждого бизнеса. Он является лицом бренда и играет ключевую роль в создании первого впечатления. Если логотип разработан опытными и креативными дизайнерами, он будет не только эстетически привлекательным, но и отражать ценности и характеристики бренда. Такой логотип быстро привлекает внимание, надолго остается в памяти покупателей и значительно повышает уровень узнаваемости бренда.",
      "price_text11": "Цена интернет-магазина",
      "price_text12": "от 14.469.000",
      "price_text13": "Более 1,92 миллиарда человек совершают покупки онлайн по всему миру, что составляет примерно четверть населения мира. Открыв интернет-магазин, вы сможете использовать эту большую аудиторию для получения значительной прибыли.Таким образом, с помощью интернет-магазина вы сможете расширить свою клиентскую базу не только на местном, но и на международном уровне и значительно увеличить свой доход.",
      "price_text14": "Цена Гугл Адворд",
      "price_text15": "от 1.894.000",
      "price_text16": "Используя рекламный сервис Google, вы сможете вывести свой сайт в топ результатов поиска Google всего за один день. Реклама через Google может значительно увеличить ваш бизнес и принести неожиданный доход. В результате использование рекламного сервиса Google является очень эффективным инструментом для дальнейшего развития вашего бизнеса и увеличения доходов.",
      "price_text17": "Стоимость брендинга",
      "price_text18": "от 1.900.000",
      "price_text19": "Выбор привлекательного названия для компании очень важен. Имя, которое вы выберете для своего бренда или фирмы, может оказать огромное влияние на его будущий успех. Подбор названия, подходящего для вашего бренда, вы можете доверить профессиональной дизайн-студии «AKILA», они помогут вам создать подходящее, впечатляющее и запоминающееся имя для вашего бизнеса.",
      "business_text1.1":"Команда CMD-TECH каждому клиенту",
      "business_text1.2":"индивидуальный подход",
      "business_text2":"Разместить заказ",
      "info_text1":"Что предлагает вам команда CMD-TECH?",
      "info_text2":"Создать сайт",
      "info_text3":"Опытные специалисты по маркетингу будут работать над увеличением вашего дохода. Работы по созданию сайта выполняются на основании конкретных технических требований и в очень быстрые сроки. Мы предлагаем разнообразные услуги, включая мобильные сайты, лендинги, корпоративные сайты, сайты объявлений и новостей, а также интернет-магазины, созданные нашей компанией.",
      "info_text4":"Сайт-визитка",
      "info_text5":"Сайт компании, как ее главная «визитная карточка» в Интернете, должен содержать самую необходимую информацию о компании. Данный сайт, как бизнес-страница, служит для ознакомления посетителей с услугами и продуктами компании.",
      "info_text6":"Одностраничный сайт",
      "info_text7":"Landing Page — одностраничный веб-сайт, спроектированный так, чтобы быть удобным для пользователя. Данная страница предназначена для предоставления клиентам необходимой информации.",
      "info_text8":"Вебсайт компании",
      "info_text9":"Сайт компании является ее официальным представительством в сети Интернет и может различаться по сложности. Основная цель – предоставить полную информацию о компании и сделать эту информацию доступной для широкой публики.",
      "info_text10":"Интернет-магазин",
      "info_text11":"Открытие интернет-магазина поможет увеличить продажи. Для этого очень важно, чтобы дизайн магазина был привлекательным и привлекал внимание.",
      "info_text12":"Эксклюзивные сайты",
      "info_text13":"Специалисты работают над созданием сайтов с нуля, каждый из которых уникален. Они создают уникальный контент и дизайн для сайта, поэтому цена таких сайтов немного выше обычных.",
      "info_text14":"Независимо от того, какой тип веб-сайта вы хотите создать, вы сможете добиться желаемых результатов с помощью опытных специалистов команды CMD-TECH.",
      "info_text_title":"Дополнительные услуги",
      "info_text15":"Создание корпоративных сайтов",
      "info_text16":"Создание сайта для туристической компании",
      "info_text17":"Поднимите свой образовательный центр на новый уровень, открыв сайт в Интернете.",
      "info_text18":"Услуга создания сайта для медицинского центра",
      "info_text19":"Сервис по открытию и созданию новостного сайта на домене UZ",
      "info_text20":"Открытие сайта юридической фирмы в Google",
      "info_text21":"Услуги по разработке сайтов для производственных предприятий",
      "info_text22":"Открытие эксклюзивного сайта для известных брендов",
      "info_text23":"Разработка технического задания для сайтов",
      "footer_text1": "Мы осчастливили более 100 клиентов. Свяжитесь с нами, чтобы узнать, как мы можем вам помочь!", 
      "footer_text2": "Лучше один раз сказать, чем сто раз прочитать. Давайте проанализируем ваш бизнес и подготовим для вас специальное предложение.", 
      "footer_text3": "Не откладывайте продвижение своего бизнеса, иначе этим воспользуется кто-то другой.", 
      "footer_text4": "Позвоните нам сейчас:", 
      "footer_text5": "Контакты", 
      "footer_text6": "Каттакоргон ул. 20, город Ташкент", 
      "footer_text7": "Меню", 
      "footer_text8": "Наши ценности",
      "footer_text9": "Команда CMD-TECH",
      "footer_text10": "Присоединиться к нашей команде",
      "footer_text11": "Контакты",
      "footer_text12": "о нас", 
      "footer_text13": "Статьи", 
      "footer_text14": "Наши образцы работ", 
      "footer_text15": "Мнения наших клиентов", 
      "footer_text16": "Проекты и публикации", 
      "footer_text17": "Подписывайтесь на нас:", 
      "footer_text2.2":"Оставить заявку",
      "": "", 
      "": "", 
      "": "", 
      "": "", 
      "": "", 
      "": "", 
      "": "", 
      "": "", 
      "": "", 
  
  
  
  
    },
    "en": {
      "home": "Create a site",
      "about": "SEO and Monetization",
      "product": "Design and Branding",
      "our_work": "Our work samples",
      "price": "Prices",
      "nav_text": "Place an order",
      "section1_text1.1": "Complete price list for  ",
      "section1_text1.2": " website development and advertising services",
      "section1_text2": "Need internet marketing services for your business? Leave it to the masters!",
      "section1_text3": "Even if the sparrow is slaughtered, let the butcher slaughter it. Save yourself from unnecessary expenses.",
      "section1_text4": "With us right now",
      "section1_text5": "Connection",
      "price_text1": "SEO Service Cost",
      "price_text2": "from 4,500,000",
      "price_text3": "One of the most popular and useful marketing services today is SEO, which is how you can rank high in the Google search engine. If your business is on the top pages of Google, it will help customers find you more easily and thus earn you more revenue. This method is one of the most effective ways to generate income for your business.",
      "price_text4": " More",
      "price_text5": "The cost of opening a site",
      "price_text6": "from 3,500,000",
      "price_text7": "Having a website for a business owner plays an important role in gaining the trust of customers. This site allows anyone to provide the necessary information about your business, its operations and the products offered, at any time. is an important tool to make the necessary changes to grow and develop your business.",
      "price_text8": "The cost of making a logo",
      "price_text9": "from 3,559,000",
      "price_text10": "A logo is a very important element for every business. It is the face of the brand and plays a key role in creating the first impression. If the logo is designed by skilled and creative designers, it will not only be aesthetically attractive, but also reflect the values ​​and characteristics of the brand. Such a logo quickly attracts attention, remains in the memory of customers for a long time and significantly increases the level of brand recognition.",
      "price_text11": "Online store price",
      "price_text12": "from 14,469,000",
      "price_text13": "More than 1.92 billion people shop online worldwide, which is roughly a quarter of the world's population. By opening an online store, you can use this large audience to make a significant profit. Thus, through an online store, you can expand your customer base not only locally, but also internationally, and significantly increase your income.",
      "price_text14": "Google Adword Price",
      "price_text15": "from 1,894,000",
      "price_text16": "Using Google advertising service, you can get your website to the top of Google search results in just one day. Advertising through Google can increase your business tremendously and generate unexpected income. As a result, using Google advertising service is a very effective tool to further develop your business and increase your income.",
      "price_text17": "The cost of branding",
      "price_text18": "from 1,900,000",
      "price_text19": "Choosing an attractive name for a company is very important. The name you choose for your brand or firm can have a huge impact on its future success. You can entrust the task of choosing a name suitable for your brand to the professional design studio 'AKILA', they will help you create a suitable, impressive and memorable name for your business.",
      "business_text1.1":"CMD-TECH team to every customer",
      "business_text1.2":"individual approach",
      "business_text2":"Place an order",
      "info_text1":"What does the CMD-TECH team offer you?",
      "info_text2":"Create a site",
      "info_text3":"Experienced marketing professionals will work to increase your income. Website creation works are performed on the basis of specific technical requirements and in a very fast time. We offer a variety of services, including mobile websites, landing pages, corporate websites, classifieds and news sites, and online stores created by our company.",
      "info_text4":"Business card site",
      "info_text5":"The company's website, as its main business card on the Internet, should contain the most necessary information about the company. This site, as a business page, serves to introduce visitors to the company's services and products.",
      "info_text6":"One page site",
      "info_text7":"A Landing Page, a one-page website, is designed to be user-friendly. This page is intended to provide customers with the necessary information.",
      "info_text8":"Company website",
      "info_text9":"A company's website is its official representation on the Internet and can vary in complexity. The main goal is to provide complete information about the company and make this information available to the general public.",
      "info_text10":"Online store",
      "info_text11":"Setting up an online store will help increase sales. For this, it is very important that the design of the store is attractive and attention-grabbing.",
      "info_text12":"Exclusive sites",
      "info_text13":"Experts work to create sites from scratch, each one unique. They create unique content and design for the site, so the price of such sites is slightly higher than usual.",
      "info_text14":"No matter what type of website you want to create, you can achieve the desired results with the help of experienced experts from the CMD-TECH team.",
      "info_text_title":"Additional services",
      "info_text15":"Creation of corporate sites",
      "info_text16":"Creating a website for a travel company",
      "info_text17":"Take your educational center to a new level by opening a website on the Internet",
      "info_text18":"Website creation service for a medical center",
      "info_text19":"Service for opening and creating a news site in the UZ domain",
      "info_text20":"Opening a site for a law firm on Google",
      "info_text21":"Website development services for manufacturing enterprises",
      "info_text22":"Opening an exclusive website for famous brands",
      "info_text23":"Development of specifications for websites",
      "footer_text1": "We have made more than 100 customers happy. Contact us to find out how we can help you!", 
      "footer_text2": "It is better to talk once than read a hundred times. Let us analyze your business and prepare a special offer for you.", 
      "footer_text3": "Don't delay promoting your business, or someone else will take advantage of it.", 
      "footer_text4": "Call us now:", 
      "footer_text5": "Connections", 
      "footer_text6": "Kattakorgon St. 20, Tashkent City",
      "footer_text7": "Menu",
      "footer_text8": "Our values",
      "footer_text9": "CMD-TECh team",
      "footer_text10": "Join our team",
      "footer_text811": "Connections",
      "footer_text12": "about Us", 
      "footer_text13": "Articles", 
      "footer_text14": "Our work samples", 
      "footer_text15": "Our customers' opinions", 
      "footer_text16": "Projects and publications", 
      "footer_text17": "Follow us:",
      "footer_text2.2": "Submit your application",
      "": "",
      "": "",
      "": "",
      "": "",
      "": "",
      "": "",
      "": "",
      "": "",
      "": "",
      "": "",  
    }
  };
  
  const langElements = document.querySelectorAll('.lang');
  
  function changeLanguage(language) {
    selectedLanguage = language;
    langElements.forEach(el => {
      el.textContent = langData[selectedLanguage][el.getAttribute('key')];
    });
  }
  
  
  
  // Tilni qayta belgilash
  let selectedLanguage = 'ru';
  langElements.forEach(el => {
    el.textContent = langData[selectedLanguage][el.getAttribute('key')];
  });
  
  const langButtons = document.querySelectorAll('.lang-button');
  langButtons.forEach(btn => {
  btn.addEventListener('click', () => {
    changeLanguage(btn.dataset.lang);
    langButtons.forEach(btn => {
      btn.classList.remove('active_lang');
    });
    btn.classList.add('active_lang');
  });
  });