const langData = {
    "uz": {
      "home": "Sayt yaratish",
      "about": "SEO va Daromadni Oshirish",
      "product": "Dizayn va Brending",
      "our_work": "Ish namunalarimiz",
      "price": "Narxlar",
      "nav_text": "Buyurtma berish",
      "section1_text1": "Veb-sayt yaratish va reklama xizmatlari uchun to'liq narx ro'yxati",
      "section1_text2": "Biznesingiz uchun internet marketing xizmatlari kerakmi? Buni faqat o’z ishining ustalariga topshiring!",
      "section1_text3": "Chumchuq so’ysa ham qassob so’ysin. O’zingizni ortiqcha xarajatlardan saqlang.",
      "section1_text4": "Hoziroq biz bilan",
      "section1_text5": "Bog'lanish",
      "our_section_text1": "Internet Marketing Xizmatlar",
      "our_section_text2": "SEO optimallashtirish",
      "our_section_text3": "SEOning maqsadi - veb-sayt yoki veb-sahifa kontentini qidiruv tizimi algoritmlari uchun qulayroq qilish orqali ko'proq trafik jalb qilishdir.",
      "our_section_text4": "Batafsil",
      "our_section_text5": "Sayt yaratish",
      "our_section_text6": "Sayt yaratish CMD_TECH jamoasi sizning biznesingiz uchun zamonaviy veb-saytlarni, internet-do'konlarni yaratadi.",
      "our_section_text7": "Googleda reklama",
      "our_section_text8": "Sizga yangi mijozlar, savdo o'sishi, ko'proq foydalanuvchi trafigini hohlaysizmi? Google-da hamyonbob narxlarda professional internet reklama, kontekstli reklama buyurtma qilishni taklif qilamiz",
      "our_section_text9": "Brend yaratish",
      "our_section_text10": "Sizning brendingiz uchun noyob va ijodiy nom izlayapsizmi? CMD_TECH jamoasi sizning biznesingizni ajralib turadigan, esda qolarli va kreativ brend identifikatsiyasi bilan ta'minlaydi. Biz sizning brendingizga o'ziga xoslik va yangilik baxsh etamiz!",
      "our_section_text11": "Logotip yasash",
      "our_section_text12": "Logotip brendga kuchli poydevor beradigan qismdir. CDM_TECH jamoasi veb-saytingizga logotip ishlab chiqishga yordam beradi.",
      "our_section_text13": "Online do'kon yaratish",
      "our_section_text14": "CMD_TECH jamoasi to'lov tizimidan foydalanish qulayligidan boshlab, boshqa tizimlar bilan integratsiyaga qila oladigan muvaffaqiyatli onlayn-do'kon yaratishga sizga yordam beradi.",
      "our_section_text15": "CRM tizimini yaratish",
      "our_section_text16": "CMD_TECH jamoasi ko'p yillar davomida kichik, o'rta va yirik biznes uchun CRM tizimlari bilan shug'ullanadi. Bu yordamida mijozlar bilan biznesni boshqarish va biznes jarayonlaringizni optimallashtirish oson.",
      "our_section_text17": "SMM xizmati",
      "our_section_text18": "SMM internet reklama xizmati: Instagram, Youtube, Facebook kabi ommabop ijtimoiy tarmoqlarda savdo hajmini oshirish uchun, auditoriyani qamrab olgan holda mijozlarni jalb qilishdan iborat.",
      "our_works_text1": "100 dan Ortiq Mamnun Mijozlarni Ishonchini Oqladik",
      "section2_text1": "Korxonamga sayt yaratish xizmati bilan qanday o’sish olib kirasizlar?",
      "section2_text2": "«Kichik mablag’ evaziga yillab reklama qilish»",
      "section2_text3": "Faqat shu shart bilan CMD-TECH kompaniyasi bilan hamkorlik qilishga rozi bo’ldim. Shunda menga sayt yaratish va uni tabiiy ravishda Googleda yuqoriga olib chiqish SEO xizmatini taklif qilishdi. SEO nimaligini uncha yaxshi tushunmasam ham, o’shanda taklifga rozi bo’ldim, chunki reklamaga katta pul tikishga na imkonim, na vaqtim bor edi. Natijada 2017 yildan beri reklama haqida o’ylamayman, lekin zakazlar to’xtagani yo’q. Kichik ishimni katta biznesga aylantirdim. Ko’plar SEO reklamani umuman hisobga olishmaydi. Menimcha, agar biznesim uzoqqa borsin desangiz, birinchi ishni shundan boshlang",
      "section2_text4": "Shuhrat, Profnastil ishlab chiqarish korxonasi asoschisi, Toshkent",
      "order_text1": "Raqobatchilaringiz ertaga bundan xabar topmasdan,",
      "order_text2": "Siz shuni bugun boshlang.",
      "order_text3": "Natijasiga mana biz turibmiz.",
      "order_text4": "Hoziroq bizga bog'laning",
      "about_text1": "Qanday Xizmat Ko'rsatasizlar",
      "about_text2": "Ish uslubimizda dunyoni eng oldi kompaniyalaridan andoza olingan. Loyihangiz uchun jon kuyduruvchilar bilan tanishing",
      "about_text3": "Loyiha boshqaruvchisi",
      "about_text4": "Sizning loyihangiz sifatiga javobgar xodim",
      "about_text5": "Mutaxassislar", 
      "about_text6": "Dizayn, marketing, dasturlash sohasidagi mutaxassislar", 
      "about_text7": "Sotuv menegeri", 
      "about_text8": "Sizni doim ishni ketishidan xabardor qiluvchi xodim", 
      "section2_4_text1": "BU MEN UCHUN HAM ZARURLIGINI TUSHUNDIM",
      "section2_4_text2": "Bizning internet marketing mutaxassislarimiz ko’plab firmalar uchun saytga tashriflar sonini, qo’ng’iroqlar sonini va, albatta, daromadni oshirib berishni. Ular bu ishlarni siz uchun ham qilishga tayyor.",
      "section2_4_text3": "Sayt yaratish uchun biznes taklif olish",
      "seo_text1": "Sayt yo’qligi xaridorlaringiz ishonchini 97% tushirib yuboradi", 
      "seo_text2": "Zamonaviy biznes olamida kuchli veb-saytga ega bo'lish, muvaffaqiyatning kalitidir. Sizning brendingiz, mahsulotlaringiz yoki xizmatlaringiz internetda to'g'ri namoyish etilganmi? Raqobatbardosh bozorda ajralib turishni istaysizmi? O'z biznesingizni keyingi bosqichga olib chiqish uchun professional veb-saytga ehtiyoj sezayotgan bo'lsangiz, biz sizga yordam berishga tayyormiz", 
      "footer_text1": "Biz 100 dan ortiq mijozlarimizni xursand qildik. Sizga qanday yordam berishimiz mumkinligini bilish uchun biz bilan bog'laning!", 
      "footer_text2": "Yuz marta o'qigandan ko'ra, bir marta gaplashish yaxshiroqdir. Sizning biznesingizni tahlil qilaylik va siz uchun maxsus taklif tayyorlaylik.", 
      "footer_text3": "O'zingizning biznesingizni targ'ib qilishni kechiktirmang, aks holda kimdir bu imkoniyatdan foydalanadi.", 
      "footer_text4": "Bizga hozir qo'ng'iroq qiling:", 
      "footer_text5": "Aloqalar", 
      "footer_text6": "Kattaqo'rg'on ko'ch. 20-uy, Toshkent Shahar", 
      "": "",
      "": "",
      "": "",
      "": "",
      "": "",
      "": "",
      "": "",
      "": "",
  
      
    },
    "ru": {
      "home": "Создать сайт",
      "about": "SEO и Увеличение дохода",
      "product": "Дизайн и Брендинг",
      "our_work": "Портфолио",
      "price": "Цены",
      "nav_text": "Разместить заказ",
      "section1_text1": "Полный прайс-лист на услуги по созданию сайтов и рекламе",
      "section1_text2": "Нужны услуги интернет-маркетинга для вашего бизнеса? Оставьте это мастерам!",
      "section1_text3": "Даже если воробья зарежут, пусть его зарежет мясник. Спасите себя от перерасхода средств.",
      "section1_text4": "С нами прямо сейчас",
      "section1_text5": "Связь",
      "our_section_text1": "Услуги интернет-маркетинга",
      "our_section_text2": "SEO-оптимизация",
      "our_section_text3": "Цель SEO — привлечь больше трафика на веб-сайт или веб-страницу, сделав их более удобными для поисковых систем.",
      "our_section_text4": "Более",
      "our_section_text5 ": "Создать сайт выф",
      "our_section_text6": "Создание сайтов Команда CMD_TECH создает современные сайты, интернет-магазины для вашего бизнеса",
      "our_section_text7": "Реклама в Google",
      "our_section_text8": "Хотите новых клиентов, роста продаж, большего пользовательского трафика? Предлагаем заказать профессиональную интернет-рекламу, контекстную рекламу в Google по доступным ценам.",
      "our_section_text9": "Создание бренда",
      "our_section_text10": "Ищете уникальное и креативное название для своего бренда? Команда CMD_TECH придаст вашему бизнесу отличительный, запоминающийся и креативный фирменный стиль. Мы придадим вашему бренду оригинальность и новаторство!",
      "our_section_text11": "Сделать логотип",
      "our_section_text12": "Логотип — это часть, которая дает прочную основу бренду. Команда CDM_TECH поможет вам разработать логотип для вашего сайта.",
      "our_section_text13": "Создать интернет-магазин",
      "our_section_text14": "Команда CMD_TECH поможет вам создать успешный интернет-магазин, начиная с простоты использования платежной системы и заканчивая интеграцией с другими системами.",
      "our_section_text15": "Создание CRM-системы",
      "our_section_text16": "Команда CMD_TECH уже много лет занимается CRM-системами для малого, среднего и крупного бизнеса. Благодаря этому легко управлять бизнесом с клиентами и оптимизировать бизнес-процессы.",
      "our_section_text17": "СММ сервис",
      "our_section_text18": "Услуга SMM интернет-рекламы: предполагает привлечение клиентов путем охвата аудитории с целью увеличения объема продаж в популярных социальных сетях, таких как Instagram, YouTube, Facebook.",
      "our_works_text1": "Мы оправдали доверие более 100 довольных клиентов",
      "section2_text1": "Как вы будете развивать мой бизнес с помощью услуг по разработке веб-сайтов?",
      "section2_text2": "«Реклама за небольшие деньги»",
      "section2_text3": "Я согласился сотрудничать с командой CMD-TECH только при этом условии. Затем мне предложили услугу SEO по созданию сайта и его естественному выводу в топ Google. Хоть я и не очень хорошо разбирался в SEO, я тогда согласился на предложение, так как у меня не было ни возможности, ни времени вкладывать большие деньги в рекламу. В итоге о рекламе я не думал с 2017 года, но заказы не прекратились. Я превратил свой маленький бизнес в большой бизнес. Многие вообще не рассматривают SEO-рекламу. На мой взгляд, если вы хотите, чтобы мой бизнес пошел далеко, начните с этого в первую очередь.",
      "section2_text4": "Шухрат, основатель производственного предприятия «Профнастил», г. Ташкент",
      "order_text1": "Прежде чем ваши конкуренты узнают об этом завтра,",
      "order_text2": "Вы начинаете сегодня.",
      "order_text3": "Вот мы и подошли к концу.", 
      "order_text4": "Свяжитесь с нами сейчас", 
      "about_text1": "Какие услуги вы предоставляете?", 
      "about_text2": "Наш стиль работы создан по образцу ведущих мировых компаний. Познакомьтесь с горелками для вашего проекта", 
      "about_text3": "Руководитель проекта", 
      "about_text4": "Человек, ответственный за качество вашего проекта", 
      "about_text5": "Специалисты", 
      "about_text6": "Специалисты в области дизайна, маркетинга, программирования", 
      "about_text7": "Менеджер по продажам", 
      "about_text8": "Сотрудник, который всегда информирует вас о том, что идет работа", 
      "section2_4_text1": "Я ПОНИМАЮ, ЧТО ЭТО НУЖНО И МНЕ",
      "section2_4_text2": "Наши специалисты по интернет-маркетингу помогли многим компаниям увеличить посещаемость сайта, звонки и, конечно же, прибыль. Они готовы сделать это и для вас.",
      "section2_4_text3": "Получите бизнес-предложение на создание сайта",
      "seo_text1": "Отсутствие веб-сайта снижает доверие ваших клиентов на 97 %.", 
      "seo_text2": "В современном деловом мире наличие качественного веб-сайта является ключом к успеху. Правильно ли представлен ваш бренд, продукты или услуги в Интернете? Хотите выделиться на конкурентном рынке? Если вам нужен профессиональный веб-сайт, чтобы вывести ваш бизнес на новый уровень, мы здесь, чтобы помочь.", 
      "footer_text1": "Мы осчастливили более 100 клиентов. Свяжитесь с нами, чтобы узнать, как мы можем вам помочь!", 
      "footer_text2": "Лучше один раз сказать, чем сто раз прочитать. Давайте проанализируем ваш бизнес и подготовим для вас специальное предложение.", 
      "footer_text3": "Не откладывайте продвижение своего бизнеса, иначе этим воспользуется кто-то другой.", 
      "footer_text4": "Позвоните нам сейчас:", 
      "footer_text5": "Контакты", 
      "footer_text6": "Каттакоргон ул. 20, город Ташкент", 
      "": "", 
      "": "", 
      "": "", 
      "": "", 
      "": "", 
      "": "", 
      "": "", 
      "": "", 
      "": "", 
  
  
  
  
    },
    "en": {
      "home": "Create a site",
      "about": "SEO and Monetization",
      "product": "Design and Branding",
      "our_work": "Our work samples",
      "price": "Prices",
      "nav_text": "Place an order",
      "section1_text1": "Complete price list for website development and advertising services",
      "section1_text2": "Need internet marketing services for your business? Leave it to the masters!",
      "section1_text3": "Even if the sparrow is slaughtered, let the butcher slaughter it. Save yourself from unnecessary expenses.",
      "section1_text4": "With us right now",
      "section1_text5": "Connection",
      "our_section_text1": "Internet Marketing Services",
      "our_section_text2": "SEO optimization",
      "our_section_text3": "The goal of SEO is to drive more traffic to a website or webpage by making it more search engine friendly.",
      "our_section_text4": "Start now",
      "our_section_text5": "Create a site",
      "our_section_text6": "Site creation CMD_TECH team creates modern websites, online stores for your business.",
      "our_section_text7": "Advertising on Google",
      "our_section_text8": "Do you want new customers, sales growth, more user traffic? We offer you to order professional internet advertising, contextual advertising on Google at affordable prices",
      "our_section_text9": "Brand building",
      "our_section_text10": "Looking for a unique and creative name for your brand? The CMD_TECH team will provide your business with a distinctive, memorable and creative brand identity. We will give your brand originality and innovation!",
      "our_section_text11": "Create a logo",
      "our_section_text12": "A logo is the part that gives a solid foundation to a brand. The CDM_TECH team will help you create a logo for your website.",
      "our_section_text13": "Create an online store",
      "our_section_text14": "The CMD_TECH team will help you create a successful online store, starting with the ease of use of the payment system and integrating it with other systems.",
      "our_section_text15": "Creating a CRM system",
      "our_section_text16": "The CMD_TECH team has been dealing with CRM systems for small, medium and large businesses for many years. With this, it is easy to manage business with customers and optimize your business processes.",
      "our_section_text17": "SMM service",
      "our_section_text18": "SMM internet advertising service: involves attracting customers by covering the audience in order to increase the volume of sales on popular social networks such as Instagram, YouTube, Facebook.",
      "our_works_text1": "We have earned the trust of over 100 satisfied customers",
      "section2_text1": "How will you grow my business with website development services?",
      "section2_text2": "Advertising for a small amount of money",
      "section2_text3": "I agreed to cooperate with CMD-TECH company only on this condition. Then I was offered an SEO service to build a site and get it to the top of Google naturally. Even though I didn't understand SEO very well, I agreed to the offer at that time, because I had neither the opportunity nor the time to invest a lot of money in advertising. As a result, I have not thought about advertising since 2017, but the orders have not stopped. I turned my small business into a big business. Many do not consider SEO advertising at all. In my opinion, if you want my business to go far, start with this first thing",
      "section2_text4": "Shuhrat, founder of Profnastil production enterprise, Tashkent",
      "order_text1": "Before your competitors find out tomorrow,",
      "order_text2": "You start today.",
      "order_text3": "Here we are at the end.",
      "order_text4": "Contact us now",
      "about_text1": "What kind of service do you provide?",
      "about_text2": "Our work style is modeled after the world's leading companies. Meet the burners for your project",
      "about_text3": "Project manager",
      "about_text4": "The person responsible for the quality of your project",
      "about_text5": "Specialists", 
      "about_text6": "Specialists in design, marketing, programming", 
      "about_text7": "Sales manager", 
      "about_text8": "An employee who always informs you that work is going on", 
      "section2_4_text1": "I UNDERSTAND THAT THIS IS NECESSARY FOR ME AS WELL",
      "section2_4_text2": "Our internet marketing experts have helped many companies increase site visits, calls and, of course, profits. They are willing to do these things for you as well.",
      "section2_4_text3": "Get a business proposal to create a website",
      "seo_text1": "Not having a website reduces the trust of your customers by 97%", 
      "seo_text2": "In today's business world, having a strong website is the key to success. Is your brand, products or services properly represented on the internet? Want to stand out in a competitive market? If you need a professional website to take your business to the next level, we're here to help", 
      "footer_text1": "We have made more than 100 customers happy. Contact us to find out how we can help you!", 
      "footer_text2": "It is better to talk once than read a hundred times. Let us analyze your business and prepare a special offer for you.", 
      "footer_text3": "Don't delay promoting your business, or someone else will take advantage of it.", 
      "footer_text4": "Call us now:", 
      "footer_text5": "Connections", 
      "footer_text6": "Kattakorgon St. 20, Tashkent City",
      "": "",
      "": "",
      "": "",
      "": "",
      "": "",
      "": "",
      "": "",
      "": "",
      "": "",
      "": "",
      "": "",  
    }
  };
  
  const langElements = document.querySelectorAll('.lang');
  
  function changeLanguage(language) {
    selectedLanguage = language;
    langElements.forEach(el => {
      el.textContent = langData[selectedLanguage][el.getAttribute('key')];
    });
  }
  
  
  
  // Tilni qayta belgilash
  let selectedLanguage = 'ru';
  langElements.forEach(el => {
    el.textContent = langData[selectedLanguage][el.getAttribute('key')];
  });
  
  const langButtons = document.querySelectorAll('.lang-button');
  langButtons.forEach(btn => {
  btn.addEventListener('click', () => {
    changeLanguage(btn.dataset.lang);
    langButtons.forEach(btn => {
      btn.classList.remove('active_lang');
    });
    btn.classList.add('active_lang');
  });
  });